version: '3.8'
services:
  solarwatch-app:
    image: mcgerasz/solarwatch-postgresql:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - postgres
    environment:
      ASPNETCORE_CONNECTIONSTRING: ${ASPNETCORE_CONNECTIONSTRING}
      ASPNETCORE_GEOLOCATORAPIKEY: ${ASPNETCORE_GEOLOCATORAPIKEY}
      ASPNETCORE_VALIDISSUER: ${ASPNETCORE_VALIDISSUER}
      ASPNETCORE_VALIDAUDIENCE: ${ASPNETCORE_VALIDAUDIENCE}
      ASPNETCORE_ISSUERSIGNINGKEY: ${ASPNETCORE_ISSUERSIGNINGKEY}
      ASPNETCORE_ADMINEMAIL: ${ASPNETCORE_ADMINEMAIL}
      ASPNETCORE_ADMINPASSWORD: ${ASPNETCORE_ADMINPASSWORD}

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Password123"
      POSTGRES_DB: "WQuizzDB"
    ports:
      - "1433:1433"
  
  solarwatch-frontend:
    image: mcgerasz/solarwatch-frontend:latest
    build:
      context: ../solarwatch-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
