version: '3.8'
services:
  solarwatch-app:
    image: solarwatch:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mssql
    environment:
      ASPNETCORE_CONNECTIONSTRING: ${ASPNETCORE_CONNECTIONSTRING}
      ASPNETCORE_GEOLOCATORAPIKEY: ${ASPNETCORE_GEOLOCATORAPIKEY}
      ASPNETCORE_VALIDISSUER: ${ASPNETCORE_VALIDISSUER}
      ASPNETCORE_VALIDAUDIENCE: ${ASPNETCORE_VALIDAUDIENCE}
      ASPNETCORE_ISSUERSIGNINGKEY: ${ASPNETCORE_ISSUERSIGNINGKEY}
      ASPNETCORE_ADMINEMAIL: ${ASPNETCORE_ADMINEMAIL}
      ASPNETCORE_ADMINPASSWORD: ${ASPNETCORE_ADMINPASSWORD}

  mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: ${DATABASE_PASSWORD}
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
