version: '3.8'
services:
  solarwatch-app:
    image: mcgerasz/solarwatch:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mssql
    environment:
      ASPNETCORE_CONNECTIONSTRING: Server=mssql,1433;Database=SolarWatchApi;User Id=sa;Password=Password123;trustServerCertificate=true;
      ASPNETCORE_GEOLOCATORAPIKEY: /YourGeolocatorAPIKey/
      ASPNETCORE_VALIDISSUER: PlaceholderIssuer
      ASPNETCORE_VALIDAUDIENCE: PlaceholderAudience
      ASPNETCORE_ISSUERSIGNINGKEY: PlaceholderSigningKey123
      ASPNETCORE_ADMINEMAIL: admin@admin.com
      ASPNETCORE_ADMINPASSWORD: AdminPassword123

  mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: Password123
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
  
  solarwatch-frontend:
    image: mcgerasz/solarwatch-frontend:latest
    build:
      context: ../solarwatch-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
