name: Docker Compose Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose --version
      - name: Build and Deploy
        env:
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          ASPNETCORE_CONNECTIONSTRING: ${{secrets.CONNECTIONSTRING}}
          ASPNETCORE_GEOLOCATORAPIKEY: ${{secrets.GEOLOCATORAPIKEY}}
          ASPNETCORE_VALIDISSUER: ${{secrets.ASPNETCORE_VALIDISSUER}}
          ASPNETCORE_VALIDAUDIENCE: ${{secrets.ASPNETCORE_VALIDAUDIENCE}}
          ASPNETCORE_ISSUERSIGNINGKEY: ${{secrets.ASPNETCORE_ISSUERSIGNINGKEY}}
          ASPNETCORE_ADMINEMAIL: ${{secrets.ASPNETCORE_ADMINEMAIL}}
          ASPNETCORE_ADMINPASSWORD: ${{secrets.ASPNETCORE_ADMINPASSWORD}}
        run: |
         cd SolarWatch 
         docker-compose -f docker-compose.yml up -d
