# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  ASPNETCORE_CONNECTIONSTRING: ${{secrets.CONNECTIONSTRING}}
  ASPNETCORE_GEOLOCATORAPIKEY: ${{secrets.GEOLOCATORAPIKEY}}
        
jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore SolarWatch/SolarWatch.sln
    - name: Build
      run: dotnet build SolarWatch/SolarWatch/SolarWatch.csproj --no-restore
    - name: Test
      run: dotnet test SolarWatch/SolarWatch.sln --no-restore --verbosity normal
    - name: Build Docker image
      run: |
        docker build -t mcgerasz/solarwatch:latest .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push mcgerasz/solarwatch:latest
      working-directory: SolarWatch
